Fix package build failures
Aslov3-devel was failing while creating packages due to changes in the [render_markdown of PyGithub](https://github.com/PyGithub/PyGithub/blob/master/github/MainClass.py#L571)  (I suspect) in the upstream  

```bash
Traceback (most recent call last):
05:08:54 worker.1 |   File "/srv/www/aslo3-devel/env/lib/python3.5/site-packages/celery/app/trace.py", line 382, in trace_task
05:08:54 worker.1 |     R = retval = fun(*args, **kwargs)
05:08:54 worker.1 |   File "/srv/www/aslo3-devel/aslo/celery_app.py", line 16, in __call__
05:08:54 worker.1 |     return TaskBase.__call__(self, *args, **kwargs)
05:08:54 worker.1 |   File "/srv/www/aslo3-devel/env/lib/python3.5/site-packages/celery/app/trace.py", line 641, in __protected_call__
05:08:54 worker.1 |     return self.run(*args, **kwargs)
05:08:54 worker.1 |   File "/srv/www/aslo3-devel/aslo/api/tasks.py", line 10, in release_process
05:08:54 worker.1 |     handle_release(gh_json)
05:08:54 worker.1 |   File "/srv/www/aslo3-devel/aslo/api/release.py", line 345, in handle_release
05:08:54 worker.1 |     gh_json['release']['body']
05:08:54 worker.1 |   File "/srv/www/aslo3-devel/aslo/api/gh.py", line 47, in render_markdown
05:08:54 worker.1 |     return g.render_markdown(message).decode()
05:08:54 worker.1 | AttributeError: 'str' object has no attribute 'decode'

```

Removing the redudant decode fixe it